# Generated by Django 6.0 on 2026-01-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_emailotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='reference',
            field=models.CharField(choices=[('REGISTER', 'REGISTER'), ('RESET_PASSWORD', 'RESET_PASSWORD')], default='REGISTER', max_length=15),
        ),
    ]
