# Generated by Django 6.0 on 2026-01-10 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False),
        ),
    ]
