# Generated by Django 6.0 on 2026-01-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body',
        ),
    ]
